version: '2'
services:
  kanban:
    image: kanban.server:v1
    ports:
    - "8080:8080"
    depends_on:
    - db
  db:
    image: postgres
    volumes:
    - ~/db:/var/lib/postgresql/data
    ports:
    - "5432:5432"
    environment:
    - POSTGRES_PASSWORD=12345678
    - POSTGRES_USER=postgres
    - POSTGRES_DB=kanban